# Generated by Django 3.0.4 on 2020-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination1', models.CharField(max_length=100)),
                ('destination2', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('carModel', models.CharField(max_length=40)),
                ('time', models.TimeField()),
                ('seatsAvailable', models.IntegerField()),
            ],
        ),
    ]
