# Generated by Django 3.0.4 on 2020-03-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200311_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='offer',
            new_name='offermodel',
        ),
    ]
