# Generated by Django 3.0.4 on 2020-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20200311_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='name',
            field=models.TextField(default='no name', max_length=30),
        ),
    ]
